#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, openLoop, encoder)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* 10.) Q: Write a program that will perform the following
  - Initialize the motor’s encoder count at zero.
  - Start the motor at full power.
  - Display encoder counts as the motor runs on the NXT display
  - When the encoder count reaches 2000, reverse the direction of the motor
  - When the encoder count reaches 4000, cut power in half.
  - When the encoder count reaches 5000, stop the motor entirely.

  A:*/

task main()
{
	nMotorEncoder[LeftMotor] = 0;
	nMotorEncoder[RightMotor] = 0;

	motor[LeftMotor] = 100;
	motor[RightMotor] = 100;

		int encoderCountLeft;
		int encoderCountRight;
	encoderCountLeft = nMotorEncoder[LeftMotor];
	encoderCountRight = nMotorEncoder[RightMotor];
	while (encoderCountLeft && encoderCountRight > 0) {
		nxtDisplayTextLine(3, "The number of encoder counts for the left motor is", encoderCountLeft);
		nxtDisplayTextLine(5, "The number of encoder counts for the right motor is", encoderCountRight);
	}

	if (nMotorEncoder[LeftMotor] == 2000 && nMotorEncoder[RightMotor] == 2000){
		motor[LeftMotor] = -100;
  	motor[RightMotor] = -100;
	} else if (nMotorEncoder[LeftMotor] == 4000 && nMotorEncoder[RightMotor] == 4000){
			motor[LeftMotor] = 50;
			motor[RightMotor] = 50;
	} else if (nMotorEncoder[LeftMotor] == 5000 && nMotorEncoder[RightMotor] == 5000){
			motor[LeftMotor] = 0;
			motor[RightMotor] = 0;
	} else{
			motor[LeftMotor] = 100;
			motor[RightMotor] = 100;
	}
}
