#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*3. Q: Write a small program that uses the function from problem 2 and prints some text representing the direction on the NXT
display.
A:*/
typedef int distance;
typedef int speed;
typedef int forward;
typedef int backward;


typedef enum DIR__;

void move(distance d, speed s);

task main(){

	function moving{
		DIR_Forward;
		DIR_Backward;
	} Direction;
	Direction DIR;
	DIR = DIR_Forward;

	/* 2. Q:Implement an enumeration defining the directions right, left, center and then the following function.
	direction get_dir_to_beacon();
	A:*/

	distance d;
	speed s;

	d = 10;
	s = 50;
	move(d, s);
}
